# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres

  redis:
    image: redis

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=selectielijst.conf.docker
      - SECRET_KEY=${SECRET_KEY:-toxua5c%l3mgn)73!2@)m6l-40+5wi597=v9r42_fnz+cwbnr0}
      - ALLOWED_HOSTS=*
      - IS_HTTPS=no
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
