---

# Ensure you have the ssh tunnel running to the db cluster AND the ssh tunnel
# to the vip-master.

- name: Deploy the Gemeentelijke Selectielijst 2017
  hosts: localhost

  vars_files:
    - vars/db_credentials.yml
    - vars/selectielijst.yml

  vars:
    # from vars/db_credentials.yml
    app_db_host: "{{ db.host }}"
    app_db_port: "{{ db.port }}"
    app_db_login_user: "{{ db_superuser.username }}"
    app_db_login_password: "{{ db_superuser.password }}"

  roles:

    - role: app-database
      vars:
        # from vars/selectielijst.yml
        app_db_name: "{{ selectielijst_db_name }}"
        app_db_user: "{{ selectielijst_db_username }}"
        app_db_password: "{{ selectielijst_db_password }}"

    - role: django-app-k8s
      vars:
        django_app_k8s_namespace: selectielijst
        django_app_k8s_domain: selectielijst.openzaak.nl

        django_app_k8s_db_host: "{{ db.privateIp }}"
        django_app_k8s_db_name: "{{ selectielijst_db_name }}"
        django_app_k8s_db_username: "{{ selectielijst_db_username }}"
        django_app_k8s_db_password: "{{ selectielijst_db_password }}"
        django_app_k8s_secret_key: "{{ selectielijst_secret_key }}"
        django_app_k8s_package_name: selectielijst
        django_app_k8s_sentry_dsn: "{{ selectielijst_sentry_dsn }}"

        django_app_k8s_version: 1.0.2
        django_app_k8s_image: "openzaak/vng-selectielijst:{{ django_app_k8s_version }}"
        django_app_k8s_instance: prod
      tags:
        - app
