---

- name: Set up the redis deployment
  k8s:
    state: present
    name: redis
    namespace: "{{ django_app_k8s_namespace }}"
    definition: "{{ lookup('template', 'redis.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes


- name: Set up the app deployment
  k8s:
    state: present
    name: app
    namespace: "{{ django_app_k8s_namespace }}"
    definition: "{{ lookup('template', 'app.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
